### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by czarekplpl** [xunhuweb/WeiXin-Payments-for-WooCommerce#1]
Hello.
In Wordpress 4.7 I got this, on the payment page:
Notice: Undefined property: xh_weixinpay_for_wc_core::$qrUrl in /var/www/beautyname.cn/public_html/wp-content/plugins/wechat-weixin-payments-for-woocommerce/xh-weixinpay-for-wc-core.php on line 418

How to fix this??

Rgds
Czarek.

**Comment by xunhuweb** [comment]
thanks and we are fixed this bugs
